version: "3"

services: 
  mysqldb:
    image: mysql
    restart: always
    env_file: ./.env
    environment:
      MYSQL_DATABASE: $MYSQL_DB
      MYSQL_USER: user
      MYSQL_PASSWORD: $MYSQL_PASS
      MYSQL_ROOT_PASSWORD: $MYSQL_PASS
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
    ports:
      - $MYSQL_LOCAL_PORT:$MYSQL_DOCKER_PORT
    volumes: 
      - db-config:/etc/mysql
      - db-data:/var/lib/mysql
      - ./db/backup/files/:/data_backup/data  
  app:
    build:
      context: .
      dockerfile: ./Dockerfile
    image: node-point
    volumes:
      - ./:/app #Volumes mapeia o código que você está escrevendo em seu sistema para o ambiente do contêiner. 
      - /app/node_modules #adiciona dependencias
    ports:
      - 3000:3000
    depends_on:
      - mysqldb

volumes: 
  db-config:
  db-data: